#!/bin/bash
OUTPUTNAME=$(basename "${1}" | cut -d'.' -f1)
if [ "${OUTPUTNAME}" = "README" ] ; then
    OUTPUTNAME=A_Weaver
fi
pandoc -o ~/Desktop/"${OUTPUTNAME}"_Resume.odt -f markdown -t odt --reference-odt=/usr/local/etc/custom-reference.odt "${1}"

