#!/bin/bash

OUTPUTNAME=$(basename "${1}" | cut -d'.' -f1)
if [ "${OUTPUTNAME}" = "README" ] ; then
    OUTPUTNAME=A_Weaver
fi
if [ $OSTYPE = 'linux-gnu' ] ; then
    if [ -d "/home/linuxbrew/.linuxbrew/Cellar/resumelinux/" ] ; then
       REFERENCE="/home/linuxbrew/.linuxbrew/Cellar/resumelinux/$(ls -t /home/linuxbrew/.linuxbrew/Cellar/resumelinux/ | head -1)/custom-reference.odt"
    else
        REFERENCE="./custom-reference.odt"
    fi
else
    if [ -e /usr/local/etc/custom-reference.odt ] ; then
        REFERENCE=/usr/local/etc/custom-reference.odt
    else
        REFERENCE="./custom-reference.odt"
    fi
fi

pandoc -o ~/Desktop/"${OUTPUTNAME}"_Resume.odt -f markdown -t odt --reference-doc="${REFERENCE}" "${1}"
